### ISSUE TITLE
Add script to run server and app at same time

### ISSUE THREAD

**Issue by VerteDinde** [burkeholland/express-react-starter#2]
Hi! Love your starter repo. You mention in your Medium article that it's possible to run both server and app simultaneously using `node server/server.js & npm start`. 

I added a small script to package.json to do this and save typing:

`"server-start": "node server/server.js & npm start"`

If you think it's worthwhile, happy to commit a small PR to add that script to the package. Thanks!

**Comment by burkeholland** [comment]
I like that! It works well. One of the reasons I've been holding off on providing a better run experience is that whatever that I experience is, I want it to "just work" with VS Code. I want to be able to ship an experience that you can fire up from the terminal, or you can just hit the little green arrow in VS Code.

I've been following [this issue](https://github.com/Microsoft/vscode/issues/2726) which attempts to address the running of an npm command as a build configuration in VS Code. However, VS Code seems to choke on running two different processes like you suggested above. 

Any thoughts there?

**Comment by auchenberg** [comment]
I ended up doing something similar in my demo app thats using create-react-app + express: https://github.com/auchenberg/timey/blob/master/package.json#L13

**Comment by burkeholland** [comment]
Thanks to @auchenberg and others, we now have a launch configuration for  VS Code that will launch both processes through the editor.

**Comment by IvRRimum** [comment]
You can just use `foreman` for that. Really easy dev too for these kind's of situations.

**Comment by khushahal-sharma** [comment]
hi @VerteDinde i am trying same your way but node and react together not working. only express starts  but react not here is my code 
"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
     "dev":"node src/Backend/Server.js &  npm  start"
  },

command : npm run dev 
 output : Express server listning on port no 5000  
and react is not starting

**Comment by khushahal-sharma** [comment]
can you please  explain requirement  of 2 package.json files  one in root structure and another in /server  folder any one please @VerteDinde @burkeholland @auchenberg @IvRRimum

**Comment by Avonavi232** [comment]
@khushahal-sharma 
Had the same problem. Solved using parallelshell package:
`"scripts": {
    "start": "parallelshell \"node server/server\" \"react-app-rewired start\"",
    ...
  },`
But, notice that I`m using [react-app-rewired](https://github.com/cdharris/react-app-rewire-hot-loader)

**Comment by OhNaNaSun** [comment]
@khushahal-sharma I solved this using [concurrently](https://github.com/kimmobrunfeldt/concurrently), it works well. 
`"start": "concurrently \"yarn mock:api\" \"yarn start-react\""`
