### ISSUE TITLE
Upgrade project to use pug instead of jade

### ISSUE THREAD

**Issue by empz** [burkeholland/express-react-starter#5]
```
warning jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
warning jade > transformers@2.1.0: Deprecated, use jstransformer
```

**Comment by tekowalsky** [comment]
jade "~1.11.0" is still listed as a dependency in /server/package.json.
jade last update was 8 years ago.
jade is also dependent on a version of constantinople with a code execution vulnerability.

jade 1.11.0 is dependent on constantinople 3.0.2
constantinople 3.0.2 has a sandbox bypass vulnerability leading to arbitrary code execution.
The earliest fixed version of constantinople is 3.1.1
